title: Pixella Chatbot Docs
description: Documentation for Pixella Chatbot
highlighter: rouge
rouge:
  theme: monokai

markdown: kramdown
theme: minima   # IMPORTANT
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Ensure custom CSS and favicon loads
include:
  - _layouts
  - _includes
  - assets

url: "https://obatechhub-inc.github.io"
baseurl: "/Pixella-chatbot"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
