theme: jekyll-theme-midnight
title: Pixella Chatbot Docs
description: Documentation for Pixella Chatbot
highlighter: rouge
rouge:
  theme: github

# Ensure custom CSS and favicon loads
include:
  - assets/css/custom.css
  - assets/css/admonition.css
  - assets/pixella_favicon.png
